### ISSUE TITLE
Split `/scale` command to `/scalex` `/scaley`?

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#19] opened 2021-11-15 19:28 UTC
Maybe it would make sense to have `/scale` split into `/scalex` and `/scaley` (or `/scale/x` or `/scaleX`).  Then we could remap `/scale` with a `def`:

```
def /scale s
    /scalex $s
    /scaley $s
```

I was going to do it, but I didn't want to screw up the cool tweening option.  What do you think?

**Comment by totalgee** [comment] 2021-11-15 22:19
What's the main reason? If it's to allow uniform scaling with a single number, why not have the existing `/scale` with one argument mean "same for X and Y"? Otherwise, how useful is it to set just x or y (without specifying the other)?

(Actually, I was going to do this, but of course the problem is then if you have two arguments, we don't know whether it's uniform scale + duration, or scale X + scale Y...)

**Comment by loopier** [comment] 2021-11-16 09:29
That's exacly what I was thinking.  Uniform scaling with just one number is what I tend to go for when typing,  and chances are that we'll be scaling uniformly more often than scaling x or y independently.  But it's a feature I think it has to have.  How about having `/scale` for uniform scaling with one argument + `dur`, and `/scalex`/`/scaley` for independent scaling?

**Comment by totalgee** [comment] 2021-11-16 09:38
Yes to uniform scaling for `/scale`, and maybe `/scale/xy`? For both components?

**Comment by loopier** [comment] 2021-11-16 10:03
ok.  I don't see the advantages over `/scale/x` `/scale/y` except it's just  one method instead of two :), but no big deal.  Go for it.

**Comment by totalgee** [comment] 2021-11-16 10:32
After discussion, we agreed on:

```
/scale actor scale [dur]
```

Where scale can be a float (uniform x/y scaling) or a comma-separated string `"0.5,2"` for separate x/y scaling.

**Comment by totalgee** [comment] 2021-11-16 22:44
Resolved by:

Change /scale to only take two arguments; /create at centre of view 43f3e43

**Closed as completed by totalgee** 2021-11-16 22:44 UTC
